# github action to build and publish to google cloud run with
# version as last 11 git has digits
#
name: "Build an publish to Google Container Registry"
on: 
  push:
    branches: 
      - master
      - add-github-action
  pull_request: 
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: "Sets environment"
      run: echo "ENVIRONMENT=staging" >> $GITHUB_ENV
      if: contains(github.ref, 'master') != true

    - name: "Sets environment"
      run: echo "ENVIRONMENT=production"
      if: contains(github.ref, 'master') 

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: 'gcloud info'

    - name: Auth in Google Cloud Artifact
      run: 'gcloud auth configure-docker europe-west1-docker.pkg.dev'

    - name: Build and push Docker image
      env:
        IMAGE_NAME: europe-west1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/discord-bot/${{ env.ENVIRONMENT }}
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
